apiVersion: v1
kind: Service
metadata:
  name: tkgi-ui
  labels:
    app: tkgi-ui
spec:
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
  selector:
    app: tkgi-ui