# Generated by Django 3.1.2 on 2020-11-09 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('uuid', models.UUIDField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=32, unique=True)),
                ('plan_name', models.SlugField(choices=[('small', 'A small plan'), ('medium', 'A medium plan')], max_length=32)),
                ('uuid', models.UUIDField()),
                ('last_action', models.CharField(max_length=100)),
                ('last_action_state', models.CharField(max_length=100)),
                ('last_action_description', models.CharField(max_length=200)),
                ('kubernetes_master_host', models.CharField(max_length=200)),
                ('kubernetes_master_port', models.IntegerField()),
                ('kubernetes_master_ip', models.CharField(blank=True, max_length=20)),
                ('kubernetes_worker_instances', models.IntegerField()),
                ('k8s_version', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
