# Generated by Django 3.1.2 on 2020-11-03 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='plan_name',
            field=models.SlugField(choices=[('small', 'A small plan'), ('medium', 'A medium plan')], max_length=32),
        ),
    ]
